# Generated by Django 5.1 on 2024-08-11 04:17

import autodatetimefields.models
import django.db.models.deletion
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('ticket_type', models.CharField(blank=True, max_length=70)),
                ('ticket_category', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(max_length=200)),
                ('budget', models.TextField(blank=True, max_length=10, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('estimated_completion', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', autodatetimefields.models.AutoDateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
