# Generated by Django 5.1 on 2024-08-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_ticket_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'Ticket'},
        ),
    ]
