# Generated by Django 5.1 on 2024-08-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
