# Generated by Django 5.1 on 2024-08-12 05:11

import autodatetimefields.models
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userdetail_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', autodatetimefields.models.AutoDateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('branch_number', models.CharField(blank=True, max_length=10, null=True)),
                ('branch_type', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=70)),
                ('branch_address', models.CharField(blank=True, max_length=60)),
                ('branch_city', models.CharField(blank=True, max_length=20)),
                ('branch_province', models.CharField(blank=True, max_length=10)),
                ('branch_pc', models.CharField(blank=True, max_length=10)),
                ('branch_phone', models.CharField(blank=True, max_length=15)),
                ('branch_fax', models.CharField(blank=True, max_length=15)),
                ('branch_url', models.CharField(blank=True, max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Branch',
            },
        ),
    ]
